/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AiTask = IDL.Record({
  'id' : IDL.Text,
  'completion' : IDL.Nat,
  'status' : IDL.Text,
  'taskType' : IDL.Text,
  'priority' : IDL.Nat,
  'affectedUrl' : IDL.Text,
});
export const AuditIssue = IDL.Record({
  'affectedPages' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'severity' : IDL.Text,
});
export const SeoIssue = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'severity' : IDL.Text,
  'recommendation' : IDL.Text,
});
export const CoreWebVitals = IDL.Record({
  'cls' : IDL.Text,
  'fcp' : IDL.Text,
  'inp' : IDL.Text,
  'lcp' : IDL.Text,
  'ttfb' : IDL.Text,
  'inpStatus' : IDL.Text,
  'lcpStatus' : IDL.Text,
  'clsStatus' : IDL.Text,
  'speedIndex' : IDL.Text,
});
export const Time = IDL.Int;
export const SeoAuditResult = IDL.Record({
  'url' : IDL.Text,
  'onPageIssues' : IDL.Vec(SeoIssue),
  'status' : IDL.Text,
  'coreWebVitals' : CoreWebVitals,
  'accessibilityScore' : IDL.Nat,
  'overallScore' : IDL.Nat,
  'performanceScore' : IDL.Nat,
  'recommendations' : IDL.Vec(IDL.Text),
  'seoScore' : IDL.Nat,
  'bestPracticesScore' : IDL.Nat,
  'timestamp' : Time,
  'technicalIssues' : IDL.Vec(SeoIssue),
});
export const Backlink = IDL.Record({
  'status' : IDL.Text,
  'domain' : IDL.Text,
  'anchorText' : IDL.Text,
  'authorityScore' : IDL.Nat,
  'linkType' : IDL.Text,
});
export const Competitor = IDL.Record({
  'domainAuthority' : IDL.Nat,
  'domain' : IDL.Text,
  'estimatedTraffic' : IDL.Nat,
  'trendDirection' : IDL.Text,
  'keywordOverlap' : IDL.Nat,
});
export const Keyword = IDL.Record({
  'difficulty' : IDL.Nat,
  'trafficValue' : IDL.Nat,
  'term' : IDL.Text,
  'positionTrend' : IDL.Int,
  'searchVolume' : IDL.Nat,
  'position' : IDL.Nat,
});
export const DashboardMetrics = IDL.Record({
  'visibilityIndex' : IDL.Nat,
  'technicalHealth' : IDL.Nat,
  'onPageScore' : IDL.Nat,
  'totalKeywordsTracked' : IDL.Nat,
  'domainRating' : IDL.Nat,
  'backlinksCount' : IDL.Nat,
});
export const SerpEntry = IDL.Record({
  'date' : Time,
  'isFeaturedSnippet' : IDL.Bool,
  'keyword' : IDL.Text,
  'position' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getAiTask' : IDL.Func([IDL.Text], [AiTask], ['query']),
  'getAllAiTasks' : IDL.Func([], [IDL.Vec(AiTask)], ['query']),
  'getAllAuditIssues' : IDL.Func([], [IDL.Vec(AuditIssue)], ['query']),
  'getAllAuditResults' : IDL.Func([], [IDL.Vec(SeoAuditResult)], ['query']),
  'getAllBacklinks' : IDL.Func([], [IDL.Vec(Backlink)], ['query']),
  'getAllCompetitors' : IDL.Func([], [IDL.Vec(Competitor)], ['query']),
  'getAllKeywords' : IDL.Func([], [IDL.Vec(Keyword)], ['query']),
  'getAuditIssue' : IDL.Func([IDL.Text], [AuditIssue], ['query']),
  'getAuditResult' : IDL.Func([IDL.Text], [IDL.Opt(SeoAuditResult)], ['query']),
  'getBacklink' : IDL.Func([IDL.Text], [Backlink], ['query']),
  'getCompetitor' : IDL.Func([IDL.Text], [Competitor], ['query']),
  'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
  'getKeyword' : IDL.Func([IDL.Text], [Keyword], ['query']),
  'getSerpHistory' : IDL.Func([], [IDL.Vec(SerpEntry)], ['query']),
  'getSerpHistoryForKeyword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SerpEntry)],
      ['query'],
    ),
  'runSeoAudit' : IDL.Func([IDL.Text], [SeoAuditResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AiTask = IDL.Record({
    'id' : IDL.Text,
    'completion' : IDL.Nat,
    'status' : IDL.Text,
    'taskType' : IDL.Text,
    'priority' : IDL.Nat,
    'affectedUrl' : IDL.Text,
  });
  const AuditIssue = IDL.Record({
    'affectedPages' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'severity' : IDL.Text,
  });
  const SeoIssue = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'severity' : IDL.Text,
    'recommendation' : IDL.Text,
  });
  const CoreWebVitals = IDL.Record({
    'cls' : IDL.Text,
    'fcp' : IDL.Text,
    'inp' : IDL.Text,
    'lcp' : IDL.Text,
    'ttfb' : IDL.Text,
    'inpStatus' : IDL.Text,
    'lcpStatus' : IDL.Text,
    'clsStatus' : IDL.Text,
    'speedIndex' : IDL.Text,
  });
  const Time = IDL.Int;
  const SeoAuditResult = IDL.Record({
    'url' : IDL.Text,
    'onPageIssues' : IDL.Vec(SeoIssue),
    'status' : IDL.Text,
    'coreWebVitals' : CoreWebVitals,
    'accessibilityScore' : IDL.Nat,
    'overallScore' : IDL.Nat,
    'performanceScore' : IDL.Nat,
    'recommendations' : IDL.Vec(IDL.Text),
    'seoScore' : IDL.Nat,
    'bestPracticesScore' : IDL.Nat,
    'timestamp' : Time,
    'technicalIssues' : IDL.Vec(SeoIssue),
  });
  const Backlink = IDL.Record({
    'status' : IDL.Text,
    'domain' : IDL.Text,
    'anchorText' : IDL.Text,
    'authorityScore' : IDL.Nat,
    'linkType' : IDL.Text,
  });
  const Competitor = IDL.Record({
    'domainAuthority' : IDL.Nat,
    'domain' : IDL.Text,
    'estimatedTraffic' : IDL.Nat,
    'trendDirection' : IDL.Text,
    'keywordOverlap' : IDL.Nat,
  });
  const Keyword = IDL.Record({
    'difficulty' : IDL.Nat,
    'trafficValue' : IDL.Nat,
    'term' : IDL.Text,
    'positionTrend' : IDL.Int,
    'searchVolume' : IDL.Nat,
    'position' : IDL.Nat,
  });
  const DashboardMetrics = IDL.Record({
    'visibilityIndex' : IDL.Nat,
    'technicalHealth' : IDL.Nat,
    'onPageScore' : IDL.Nat,
    'totalKeywordsTracked' : IDL.Nat,
    'domainRating' : IDL.Nat,
    'backlinksCount' : IDL.Nat,
  });
  const SerpEntry = IDL.Record({
    'date' : Time,
    'isFeaturedSnippet' : IDL.Bool,
    'keyword' : IDL.Text,
    'position' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getAiTask' : IDL.Func([IDL.Text], [AiTask], ['query']),
    'getAllAiTasks' : IDL.Func([], [IDL.Vec(AiTask)], ['query']),
    'getAllAuditIssues' : IDL.Func([], [IDL.Vec(AuditIssue)], ['query']),
    'getAllAuditResults' : IDL.Func([], [IDL.Vec(SeoAuditResult)], ['query']),
    'getAllBacklinks' : IDL.Func([], [IDL.Vec(Backlink)], ['query']),
    'getAllCompetitors' : IDL.Func([], [IDL.Vec(Competitor)], ['query']),
    'getAllKeywords' : IDL.Func([], [IDL.Vec(Keyword)], ['query']),
    'getAuditIssue' : IDL.Func([IDL.Text], [AuditIssue], ['query']),
    'getAuditResult' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SeoAuditResult)],
        ['query'],
      ),
    'getBacklink' : IDL.Func([IDL.Text], [Backlink], ['query']),
    'getCompetitor' : IDL.Func([IDL.Text], [Competitor], ['query']),
    'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
    'getKeyword' : IDL.Func([IDL.Text], [Keyword], ['query']),
    'getSerpHistory' : IDL.Func([], [IDL.Vec(SerpEntry)], ['query']),
    'getSerpHistoryForKeyword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SerpEntry)],
        ['query'],
      ),
    'runSeoAudit' : IDL.Func([IDL.Text], [SeoAuditResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };