/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiTask {
  'id' : string,
  'completion' : bigint,
  'status' : string,
  'taskType' : string,
  'priority' : bigint,
  'affectedUrl' : string,
}
export interface AuditIssue {
  'affectedPages' : bigint,
  'title' : string,
  'description' : string,
  'category' : string,
  'severity' : string,
}
export interface AuditIssueDetail {
  'issueType' : string,
  'description' : string,
  'priority' : string,
  'impact' : string,
  'fix' : string,
  'effort' : string,
  'category' : string,
  'beforeExample' : string,
  'afterExample' : string,
}
export interface Backlink {
  'status' : string,
  'domain' : string,
  'anchorText' : string,
  'authorityScore' : bigint,
  'linkType' : string,
}
export interface Competitor {
  'domainAuthority' : bigint,
  'domain' : string,
  'estimatedTraffic' : bigint,
  'trendDirection' : string,
  'keywordOverlap' : bigint,
}
export interface CoreWebVitals {
  'cls' : string,
  'fcp' : string,
  'inp' : string,
  'lcp' : string,
  'ttfb' : string,
  'inpStatus' : string,
  'lcpStatus' : string,
  'clsStatus' : string,
  'speedIndex' : string,
}
export interface DashboardMetrics {
  'visibilityIndex' : bigint,
  'technicalHealth' : bigint,
  'onPageScore' : bigint,
  'totalKeywordsTracked' : bigint,
  'domainRating' : bigint,
  'backlinksCount' : bigint,
}
export interface Keyword {
  'difficulty' : bigint,
  'trafficValue' : bigint,
  'term' : string,
  'positionTrend' : bigint,
  'searchVolume' : bigint,
  'position' : bigint,
}
export interface OnPageData {
  'titleLength' : bigint,
  'titleText' : string,
  'metaDescLength' : bigint,
  'hasH1' : boolean,
  'h1Count' : bigint,
  'hasSchema' : boolean,
  'serpPixelWidth' : bigint,
  'hasCanonical' : boolean,
  'isHttps' : boolean,
}
export interface ContentData {
  'wordCount' : bigint,
  'isThinContent' : boolean,
  'keywordDensity' : string,
  'duplicateScore' : bigint,
}
export interface MediaData {
  'imageCount' : bigint,
  'missingAltCount' : bigint,
  'largeImageCount' : bigint,
}
export interface InternationalData {
  'hasHreflang' : boolean,
  'hreflangCount' : bigint,
  'missingReturnTags' : boolean,
}
export interface ArchitectureData {
  'crawlDepth' : bigint,
  'internalLinkCount' : bigint,
  'isOrphan' : boolean,
  'internalLinkScore' : bigint,
}
export interface EducationData {
  'hasBookSchema' : boolean,
  'hasProductSchema' : boolean,
  'indexingGapsDetected' : boolean,
  'cbseContentScore' : bigint,
}
export interface UrlAuditResult {
  'url' : string,
  'healthScore' : bigint,
  'timestamp' : Time,
  'issues' : Array<AuditIssueDetail>,
  'onPageData' : OnPageData,
  'contentData' : ContentData,
  'mediaData' : MediaData,
  'internationalData' : InternationalData,
  'architectureData' : ArchitectureData,
  'educationData' : EducationData,
  'performanceScore' : bigint,
  'seoScore' : bigint,
  'accessibilityScore' : bigint,
  'coreWebVitals' : CoreWebVitals,
  'status' : string,
}
export interface BulkAuditResult {
  'totalUrls' : bigint,
  'completedUrls' : bigint,
  'siteHealthScore' : bigint,
  'totalIssues' : bigint,
  'criticalIssues' : bigint,
  'results' : Array<UrlAuditResult>,
  'timestamp' : Time,
}
export interface CrawlSchedule {
  'id' : string,
  'name' : string,
  'urls' : Array<string>,
  'frequency' : string,
  'nextRun' : bigint,
  'lastRun' : [] | [bigint],
  'isActive' : boolean,
}
export interface ProjectHistoryEntry {
  'id' : string,
  'name' : string,
  'urlCount' : bigint,
  'siteHealthScore' : bigint,
  'issuesFound' : bigint,
  'createdAt' : bigint,
}
export interface SeoAuditResult {
  'url' : string,
  'onPageIssues' : Array<SeoIssue>,
  'status' : string,
  'coreWebVitals' : CoreWebVitals,
  'accessibilityScore' : bigint,
  'overallScore' : bigint,
  'performanceScore' : bigint,
  'recommendations' : Array<string>,
  'seoScore' : bigint,
  'bestPracticesScore' : bigint,
  'timestamp' : Time,
  'technicalIssues' : Array<SeoIssue>,
}
export interface SeoIssue {
  'title' : string,
  'description' : string,
  'category' : string,
  'severity' : string,
  'recommendation' : string,
}
export interface SerpEntry {
  'date' : Time,
  'isFeaturedSnippet' : boolean,
  'keyword' : string,
  'position' : bigint,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'deleteSchedule' : ActorMethod<[string], undefined>,
  'getAiTask' : ActorMethod<[string], AiTask>,
  'getAllAiTasks' : ActorMethod<[], Array<AiTask>>,
  'getAllAuditIssues' : ActorMethod<[], Array<AuditIssue>>,
  'getAllAuditResults' : ActorMethod<[], Array<SeoAuditResult>>,
  'getAllBacklinks' : ActorMethod<[], Array<Backlink>>,
  'getAllCompetitors' : ActorMethod<[], Array<Competitor>>,
  'getAllKeywords' : ActorMethod<[], Array<Keyword>>,
  'getAllUrlAuditResults' : ActorMethod<[], Array<UrlAuditResult>>,
  'getAuditIssue' : ActorMethod<[string], AuditIssue>,
  'getAuditResult' : ActorMethod<[string], [] | [SeoAuditResult]>,
  'getBacklink' : ActorMethod<[string], Backlink>,
  'getCompetitor' : ActorMethod<[string], Competitor>,
  'getDashboardMetrics' : ActorMethod<[], DashboardMetrics>,
  'getKeyword' : ActorMethod<[string], Keyword>,
  'getProjectHistory' : ActorMethod<[], Array<ProjectHistoryEntry>>,
  'getSchedules' : ActorMethod<[], Array<CrawlSchedule>>,
  'getSerpHistory' : ActorMethod<[], Array<SerpEntry>>,
  'getSerpHistoryForKeyword' : ActorMethod<[string], Array<SerpEntry>>,
  'getSiteHealthScore' : ActorMethod<[], bigint>,
  'getUrlAuditResult' : ActorMethod<[string], [] | [UrlAuditResult]>,
  'runBulkAudit' : ActorMethod<[Array<string>], BulkAuditResult>,
  'runSeoAudit' : ActorMethod<[string], SeoAuditResult>,
  'runUrlAudit' : ActorMethod<[string], UrlAuditResult>,
  'saveProjectHistory' : ActorMethod<[ProjectHistoryEntry], undefined>,
  'saveSchedule' : ActorMethod<[CrawlSchedule], undefined>,
  'toggleSchedule' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
