/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SeoIssue {
    title: string;
    description: string;
    category: string;
    severity: string;
    recommendation: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface Competitor {
    domainAuthority: bigint;
    domain: string;
    estimatedTraffic: bigint;
    trendDirection: string;
    keywordOverlap: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SerpEntry {
    date: Time;
    isFeaturedSnippet: boolean;
    keyword: string;
    position: bigint;
}
export interface AuditIssue {
    affectedPages: bigint;
    title: string;
    description: string;
    category: string;
    severity: string;
}
export interface AiTask {
    id: string;
    completion: bigint;
    status: string;
    taskType: string;
    priority: bigint;
    affectedUrl: string;
}
export interface Keyword {
    difficulty: bigint;
    trafficValue: bigint;
    term: string;
    positionTrend: bigint;
    searchVolume: bigint;
    position: bigint;
}
export interface Backlink {
    status: string;
    domain: string;
    anchorText: string;
    authorityScore: bigint;
    linkType: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface DashboardMetrics {
    visibilityIndex: bigint;
    technicalHealth: bigint;
    onPageScore: bigint;
    totalKeywordsTracked: bigint;
    domainRating: bigint;
    backlinksCount: bigint;
}
export interface CoreWebVitals {
    cls: string;
    fcp: string;
    inp: string;
    lcp: string;
    ttfb: string;
    inpStatus: string;
    lcpStatus: string;
    clsStatus: string;
    speedIndex: string;
}
export interface SeoAuditResult {
    url: string;
    onPageIssues: Array<SeoIssue>;
    status: string;
    coreWebVitals: CoreWebVitals;
    accessibilityScore: bigint;
    overallScore: bigint;
    performanceScore: bigint;
    recommendations: Array<string>;
    seoScore: bigint;
    bestPracticesScore: bigint;
    timestamp: Time;
    technicalIssues: Array<SeoIssue>;
}
export interface backendInterface {
    getAiTask(id: string): Promise<AiTask>;
    getAllAiTasks(): Promise<Array<AiTask>>;
    getAllAuditIssues(): Promise<Array<AuditIssue>>;
    getAllAuditResults(): Promise<Array<SeoAuditResult>>;
    getAllBacklinks(): Promise<Array<Backlink>>;
    getAllCompetitors(): Promise<Array<Competitor>>;
    getAllKeywords(): Promise<Array<Keyword>>;
    getAuditIssue(title: string): Promise<AuditIssue>;
    getAuditResult(url: string): Promise<SeoAuditResult | null>;
    getBacklink(domain: string): Promise<Backlink>;
    getCompetitor(domain: string): Promise<Competitor>;
    getDashboardMetrics(): Promise<DashboardMetrics>;
    getKeyword(term: string): Promise<Keyword>;
    getSerpHistory(): Promise<Array<SerpEntry>>;
    getSerpHistoryForKeyword(keyword: string): Promise<Array<SerpEntry>>;
    runSeoAudit(url: string): Promise<SeoAuditResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { SeoAuditResult as _SeoAuditResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAiTask(arg0: string): Promise<AiTask> {
        if (this.processError) {
            try {
                const result = await this.actor.getAiTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAiTask(arg0);
            return result;
        }
    }
    async getAllAiTasks(): Promise<Array<AiTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAiTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAiTasks();
            return result;
        }
    }
    async getAllAuditIssues(): Promise<Array<AuditIssue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAuditIssues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAuditIssues();
            return result;
        }
    }
    async getAllAuditResults(): Promise<Array<SeoAuditResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAuditResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAuditResults();
            return result;
        }
    }
    async getAllBacklinks(): Promise<Array<Backlink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBacklinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBacklinks();
            return result;
        }
    }
    async getAllCompetitors(): Promise<Array<Competitor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCompetitors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCompetitors();
            return result;
        }
    }
    async getAllKeywords(): Promise<Array<Keyword>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKeywords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKeywords();
            return result;
        }
    }
    async getAuditIssue(arg0: string): Promise<AuditIssue> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditIssue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditIssue(arg0);
            return result;
        }
    }
    async getAuditResult(arg0: string): Promise<SeoAuditResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditResult(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditResult(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBacklink(arg0: string): Promise<Backlink> {
        if (this.processError) {
            try {
                const result = await this.actor.getBacklink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBacklink(arg0);
            return result;
        }
    }
    async getCompetitor(arg0: string): Promise<Competitor> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompetitor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompetitor(arg0);
            return result;
        }
    }
    async getDashboardMetrics(): Promise<DashboardMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics();
            return result;
        }
    }
    async getKeyword(arg0: string): Promise<Keyword> {
        if (this.processError) {
            try {
                const result = await this.actor.getKeyword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKeyword(arg0);
            return result;
        }
    }
    async getSerpHistory(): Promise<Array<SerpEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSerpHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSerpHistory();
            return result;
        }
    }
    async getSerpHistoryForKeyword(arg0: string): Promise<Array<SerpEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSerpHistoryForKeyword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSerpHistoryForKeyword(arg0);
            return result;
        }
    }
    async runSeoAudit(arg0: string): Promise<SeoAuditResult> {
        if (this.processError) {
            try {
                const result = await this.actor.runSeoAudit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runSeoAudit(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SeoAuditResult]): SeoAuditResult | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
